<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="6" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-26T09:58:44 EDT" name="Suite" finished-at="2024-07-26T09:58:51 EDT" duration-ms="6977">
    <groups>
    </groups>
    <test started-at="2024-07-26T09:58:44 EDT" name="Test" finished-at="2024-07-26T09:58:51 EDT" duration-ms="6977">
      <class name="com.github.tests.CRUD.ValidateGetAddUpdateDeleteData">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:com.github.tests.CRUD.ValidateGetAddUpdateDeleteData@1cbb87f3]" started-at="2024-07-26T09:58:44 EDT" name="beforeSuite" finished-at="2024-07-26T09:58:44 EDT" duration-ms="81" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.github.tests.CRUD.ValidateGetAddUpdateDeleteData@1cbb87f3]" started-at="2024-07-26T09:58:44 EDT" name="beforeClass" finished-at="2024-07-26T09:58:45 EDT" duration-ms="517" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="validateGetSingleRepo()[pri:1, instance:com.github.tests.CRUD.ValidateGetAddUpdateDeleteData@1cbb87f3]" started-at="2024-07-26T09:58:45 EDT" name="validateGetSingleRepo" description="Get single data functionality" finished-at="2024-07-26T09:58:47 EDT" duration-ms="2020" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateGetSingleRepo -->
        <test-method signature="validateGetAllRepo()[pri:2, instance:com.github.tests.CRUD.ValidateGetAddUpdateDeleteData@1cbb87f3]" started-at="2024-07-26T09:58:47 EDT" name="validateGetAllRepo" description="Get all data functionality" finished-at="2024-07-26T09:58:48 EDT" duration-ms="1412" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateGetAllRepo -->
        <test-method signature="validatInvalidSingleRepo()[pri:3, instance:com.github.tests.CRUD.ValidateGetAddUpdateDeleteData@1cbb87f3]" started-at="2024-07-26T09:58:48 EDT" name="validatInvalidSingleRepo" description="Get invalid data functionality" finished-at="2024-07-26T09:58:49 EDT" duration-ms="146" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatInvalidSingleRepo -->
        <test-method signature="validateAddDataFunctionality()[pri:4, instance:com.github.tests.CRUD.ValidateGetAddUpdateDeleteData@1cbb87f3]" started-at="2024-07-26T09:58:49 EDT" name="validateAddDataFunctionality" description="Addrepo data functionality" finished-at="2024-07-26T09:58:49 EDT" duration-ms="824" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateAddDataFunctionality -->
        <test-method signature="validateAddInvalidDataFunctionality()[pri:5, instance:com.github.tests.CRUD.ValidateGetAddUpdateDeleteData@1cbb87f3]" started-at="2024-07-26T09:58:49 EDT" name="validateAddInvalidDataFunctionality" description="Add invalid repo functionality" finished-at="2024-07-26T09:58:51 EDT" duration-ms="1337" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateAddInvalidDataFunctionality -->
        <test-method signature="validateUpdateDataFunctionality()[pri:6, instance:com.github.tests.CRUD.ValidateGetAddUpdateDeleteData@1cbb87f3]" started-at="2024-07-26T09:58:51 EDT" name="validateUpdateDataFunctionality" description="Update data functionality" finished-at="2024-07-26T09:58:51 EDT" duration-ms="227" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Update data functionality is not working as expected. expected [200] but found [307]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Update data functionality is not working as expected. expected [200] but found [307]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at com.github.tests.CRUD.ValidateGetAddUpdateDeleteData.validateUpdateDataFunctionality(ValidateGetAddUpdateDeleteData.java:127)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUpdateDataFunctionality -->
        <test-method signature="validateDeleteRepo()[pri:7, instance:com.github.tests.CRUD.ValidateGetAddUpdateDeleteData@1cbb87f3]" started-at="2024-07-26T09:58:51 EDT" name="validateDeleteRepo" description="delete repo functionality" finished-at="2024-07-26T09:58:51 EDT" duration-ms="137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDeleteRepo -->
      </class> <!-- com.github.tests.CRUD.ValidateGetAddUpdateDeleteData -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
